#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx run-many --all --target=lint --parallel
npx nx run-many --all --target=test --parallel
npx nx e2e web-e2e --env.NX_FAKE_LOGIN_EMAIL=hunter@abyss.com --env.NX_FAKE_LOGIN_PASSWORD=plus_ultra 
