name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NX_FAKE_LOGIN_EMAIL: hunter@abyss.com
  NX_FAKE_LOGIN_PASSWORD: plus_ultra
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install Dependencies
        run: npm ci -f

      - name: Run Workspace Linting
        run: npx nx workspace-lint
      - name: Run NX Lint Affected Project
        run: npx nx affected --target=lint --parallel=3
      - name: Run NX Test Affected Project
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
